development:
  host: 10.1.6.106
  database: hack
  adapter: postgis
  pool: 5
  timeout: 5000
  username: housing
  password: housing

test:
  host: 10.1.6.106
  database: hack
  adapter: postgis
  pool: 5
  timeout: 5000
  username: housing
  password: housing

production:
  host: 10.1.6.106
  database: hack
  adapter: postgis
  pool: 5
  timeout: 5000
  username: housing
  password: housing
